### PR TITLE
update to fix potentially flaky css selector; allow local .ruby-version file

### PR DESCRIPTION
**Pull request by peetucket**

### CODE REVIEW

**Comment by cbeer** [comment]
Should these changes be in two separate commits? 

Could you also expand the commit message to include the rationale behind `:first` -> `:first-child`? It seems like valuable context for the future (I know I have moments of remembering fixing something in a project, and the commit message is both a good way to discover it and remind me why we made those changes)

**Comment by jkeck** [comment]
Sorry @peetucket, going to need a rebase on this.  :+1: though.

**Comment by cbeer** [comment]
:+1: Thanks, much appreciated.

**Comment by ndushay** [comment]
as the suggestions were implemented, and this was very tiny so there didn't seem anything else possibly to worry about, I merged this one.

**Pull request merged**
