### PR TITLE
Use bootstrap nav styling for the sidenav

### PR DESCRIPTION
**Pull request by cbeer**
screen shot 2015-12-16 at 8 49 58 am
screen shot 2015-12-16 at 8 50 01 am
screen shot 2015-12-16 at 8 54 32 am

### CODE REVIEW

**Comment by cbeer** [comment]
The default padding seems a little extreme, but there's a variable we can tweak locally if we want to.

**Comment by ggeisler** [comment]
Well, this is definitely a case where I don't see how any implementor would want to use that styling, but if you think it's better adjusted in the implementing app, that's fine.

**Comment by cbeer** [comment]
Apparently someone with bootstrap thinks the style is great, but they've helpfully left a variable we can change downstream:

https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L427

**Comment by ggeisler** [comment]
Yep. And maybe this is just another instance of a style that works better on other types of sites, and it's just in our context where it seems like an unusual amount of vertical padding...

**Pull request merged**
