### PR TITLE
extract exhibit functionality into module fixes #1344

### LINKED ISSUE #1344: What is the best way to override Exhibit#solr_data?
we're currently defining our own `app/models/spotlight/exhibit.rb` and requiring `Spotlight::Engine.root + 'app/models/spotlight/exhibit'` then overriding. This is not autoload safe (we have to restart our server after each change). Is there a better way?

### PR DESCRIPTION
**Pull request by ronan-mch**

### CODE REVIEW

**Comment by cbeer** [comment]
How does this fix #1345?

**Comment by ronan-mch** [comment]
Hi, see our downstream app for an [implementation of an overridehttps://github.com/dtulibrary/ddf/blob/spotlight/app/models/spotlight/exhibit.rb). Otherwise we would have to monkey patch the class as described by @jcoyne in #1344

**Comment by cbeer** [comment]
If that's all you're trying to do to, you can also set:

`Spotlight::Engine.config.filter_resources_by_exhibit = false`

in an initializer.

https://github.com/sul-dlss/spotlight/blob/master/lib/spotlight/engine.rb#L75

**Comment by jcoyne** [comment]
We're just doing no filtering right now. Eventually we want to filter the exhibit by a custom ORCID field

**Comment by jcoyne** [comment]
@cbeer if you don't like this approach, we could make `solr_data` run a Proc that is set in the Spotlight configuration.  Would you like that better?

**Comment by cbeer** [comment]
I think that sounds better, yeah. It makes me nervous to move some of the things into that module, as some of it isn't portable to any arbitrary model, and hopefully a `Proc` makes our intent more obvious too.

**Pull request closed without merging**
