### PR TITLE
Allow site admins to manage other site admins

### LINKED ISSUE #849: Allow additional super-admins to be created via the GUI
The current GUI has no way for the administrator to create additional admins.  Only admins of exhibits can currently be created.

### PR DESCRIPTION
**Pull request by jkeck**
Closes #849 

admin-user-admin

### CODE REVIEW

**Comment by jkeck** [comment]
There is a bit of a spacing issue in the form where the label has `.sr-only` as well as a `.col-md-2` but the `.col-*` declaration is keeping the allotted space available.  I don't see why the `.col-*` class isn't being added other places where we're using `hide_label: true`.

If anybody has any ideas as to why this is happening or proposed solutions, I'm all ears.

**Comment by jkeck** [comment]
Odd about the reduced coverage.  I think it's caused by relevant lines of code being moved, but that code is tested elsewhere (and showing 100% coverage). It seems odd to me that this would cause a drop of 0.2%.

**Comment by cbeer** [comment]
Agreed about the coverage; the coveralls report is less than helpful.

Should we wait to merge this until we can look at the label spacing problem?

**Comment by jkeck** [comment]
Yeah, maybe I can show you what is going on.  It's pretty minor so we can fix it up and :shipit: later today or tomorrow.

**Comment by cbeer** [comment]
:ok_hand:

**Comment by cbeer** [comment]
I've fixed the label padding problem  -- it looks like the horizontal form layout (which we didn't actually seem to need) forced columns on us. 

screen shot 2016-01-07 at 8 09 24 am

**Comment by ggeisler** [comment]
:+1:

**Comment by jkeck** [comment]
Ah!  Makes perfect sense.  Thanks @cbeer!  I'll rebase this and re-push as well.

**Comment by cbeer** [comment]
I'm not sure about perfect sense, but it probably helps keeping things aligned (and if we weren't using tables, we might need it..)

**Pull request merged**
