### PR TITLE
Add ability to upload and crop a site masthead image

### PR DESCRIPTION
**Pull request by jkeck**
Begins work on #909 by adding just local file upload.

adding-masthead

### CODE REVIEW

**Comment by jkeck** [comment]
Have yet to scale the crop image because of a bug in jcrop tapmodo/Jcrop#40.

We may need to end up forking jcrop and merging in tapmodo/Jcrop#152 but I thought I would plug away at feature now w/ the full-sized image.

**Comment by mejackreed** [comment]
:+1: Looks good to me. One jarring thing was when uploading an image, where it ended up and where the resize box was kind of jarring. Not sure if that has anything to do with the jcrop issue. I say :shipit:

**Comment by jkeck** [comment]
@mejackreed I'm going to look into forking Jcrop and applying at least one pending PR that will allow us to scale the image to a max with.  I'm hoping that will address that issue.

**Comment by jkeck** [comment]
And thanks for the :eyes:

**Pull request merged**
