### PR TITLE
Use ordinary facet and show fields for exhibit-specific tags

### LINKED ISSUE #866: Records with only a single tag look funny
e.g. https://exhibits.stanford.edu/maps-of-africa/spotlight/default-exhibit/catalog/kk053qk9156

### PR DESCRIPTION
**Pull request by cbeer**
Requires https://github.com/projectblacklight/blacklight/pull/1149

Fixes #866

### CODE REVIEW

**Comment by jkeck** [comment]
@cbeer should we :ship: this now or wait for Blacklight 5.11.1?

**Comment by cbeer** [comment]
We need to wait.

**Comment by cbeer** [comment]
But not for very long.

**Comment by cbeer** [comment]
:ok_hand:

**Comment by jkeck** [comment]
@cbeer I'm not getting any search results when clicking on an exhibit tag from a record page.  I get the expected results in master.

**Comment by cbeer** [comment]
Yep, Blacklight is screwing something /else/ up now, and i guess we don't have any test coverage here or there.

**Comment by cbeer** [comment]
https://github.com/projectblacklight/blacklight/pull/1150

**Comment by jkeck** [comment]
Just verified by running spotlight against projectblacklight/blacklight#1150  :+1:

**Comment by cbeer** [comment]
Awesome. I'll cut yet another release soon.

**Comment by cbeer** [comment]
I think we also need https://github.com/projectblacklight/blacklight/pull/1157.

**Pull request merged**
