### PR TITLE
Add Spotlight::Site model and scaffolding to manage site-wide configuration and updates

### LINKED ISSUE #1325: Enable super-admin to customize appearance of exhibits home
A super-admin should be able to add a custom masthead to the exhibits home header, and add a custom title and subtitle. The link "Customize appearance," linked from the new sidebar (#1323), should go to a new page with two tabs. 

Page header of new page: "Customize appearance"
Secondary header: "Exhibits home" (a couple of the screenshots below say "Exhibits landing page" but go with "Exhibits home," as in the last screenshot).

### Title tab
Enable super-admin to add a title and subtitle. Use those in the masthead, pretty much exactly the same as we do in individual exhibits. We haven't discussed this, but how about we add a default title of "Exhibits Home" to the masthead when the app is generated, and then we can make title a required field (subtitle would be optional; again, just mimicking what we do when creating a new exhibit)?

landing-edit-appearance-title

--
### Masthead tab

Simplified version of what we do when editing an exhibit. Here's the text (slightly different from single exhibit text):

>
You can select and crop an image to use as a background in your exhibits home masthead. To use an image as a masthead background, you should use an image that is at least 120 pixels tall and 1200 pixels wide. For best results use an image at least 1800 pixels wide. You can crop larger images using the cropping tool below.

landing-edit-appearance-masthead
--
landing-edit-appearance-masthead-2

### PR DESCRIPTION
**Pull request by cbeer**
This doesn't do much yet, just getting the scaffolding in place for #1323, #1326, etc.

Also fixes #1325

screen shot 2015-12-15 at 8 02 20 am
screen shot 2015-12-15 at 8 02 37 am
screen shot 2015-12-15 at 8 04 00 am
screen shot 2015-12-15 at 8 05 16 am
screen shot 2015-12-15 at 8 06 00 am
screen shot 2015-12-15 at 8 08 54 am

screen shot 2015-12-15 at 9 37 54 am
screen shot 2015-12-15 at 9 38 10 am

### CODE REVIEW

**Comment by jkeck** [comment]
Implementation looks good.  Don't know if we should do anything about those scss issues.  Perhaps we should relax the rules on some of them.

Also, this is going to need a rebase.

**Comment by cbeer** [comment]
Sure, I think they're due for a refactor. We'll want to do it soon anyway.

**Comment by cbeer** [comment]
Ok, I took more of the violations I was introducing at least. Hopefully we can take care of the rest as part of #1325. I'd like to talk over some refactoring ideas I had, because some of the existing logic is pretty confusing.

**Comment by cbeer** [comment]
I'm not sure that drop in coverage is real, it may be from removing lines of code?

**Pull request merged**
