### PR TITLE
Pull batch indexing and exhibit-specific data logic up from spotlight-dor-resources

### PR DESCRIPTION
**Pull request by cbeer**
I hope this will let us simplify `Spotlight::Resources::DorResource` to just the glue code with `gdor-indexer`.

### CODE REVIEW

**Comment by cbeer** [comment]
I think this should simplify Spotlight::Resources::DorResource down to something like:

```ruby
module Spotlight::Resources
  class DorResource < Spotlight::Resource
    def to_solr
      return to_enum :to_solr unless block_given?
      
      base_doc = super
      
      [resource, (resource.items if resource.collection?)].flatten.compact.each do |res|
        yield base_doc.merge(Spotlight::Dor::Resources.indexer.solr_document(res))
      end
    end
    
    private
    
    def resource
      @resource ||= Spotlight::Dor::Resources.indexer.resource doc_id
    end
  end
end
```

**Comment by ndushay** [comment]
@peetucket should there be a ticket for the simplification Chris indicates above for Spotlight::Resources::DorResource

**Comment by cbeer** [comment]
:+1:

**Comment by peetucket** [comment]
Simplication ticket: sul-dlss/spotlight-dor-resources#6

**Comment by ndushay** [comment]
:+1:

**Pull request merged**
